name: Lint PR

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-24.04
    steps:
      - uses: amannn/action-semantic-pull-request@v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scopes: |
            config
            server
            deps
            docs
            ci
            fs
            s3
            gdrive
            dropbox
            gcs
            sftp
            mail
            telegram
            keycloak
            docker
            release
          requireScope: false
